# https://github.com/myhomeiot/DahuaVTO
sensor:
  - platform: dahua_vto
    name: Citofono
    host: !secret Camera_Citofono_ip
    username: !secret Camera_Cancelletto_user
    password: !secret Camera_Cancelletto_password
    scan_interval: 5

timer:
  cancelletto_lock:
    name: Chiusura Cancelletto
    icon: mdi:timer

lock:
  - platform: template
    unique_id: '0a7476cc-d6c1-40ba-8ae1-606518c3497f'
    name: Serratura Cancelletto
    value_template: "{{ not is_state('timer.cancelletto_lock', 'active') }}"
    optimistic: false
    lock:
      - service: dahua_vto.open_door
        data:
          entity_id: sensor.citofono
          channel: 1
          short_number: HA
    unlock:
      - service: dahua_vto.open_door
        data:
          entity_id: sensor.citofono
          channel: 1
          short_number: HA

automation:
  - alias: Dahua VTO All Events
    mode: queued
    trigger:
      - platform: event
        event_type: dahua_vto
    action:
      - service: persistent_notification.create
        data:
          title: "{{ trigger.event.data.Code if trigger.event.data.Code is defined else 'Unknown Code' }}"
          message: "{{ trigger.event.data }}"
  
  - alias: Dahua VTO Command Result
    mode: queued
    trigger:
      - platform: event
        event_type: dahua_vto
    condition:
      - condition: template
        value_template: "{{ trigger.event.data.method is defined }}"
    action:
      - service: persistent_notification.create
        data:
          title: "{{ trigger.event.data.method }}"
          message: "{{ trigger.event.data }}"
  
  - alias: Dahua VTO
    mode: queued
    trigger:
      - platform: event
        event_type: dahua_vto
        event_data:
          Code: BackKeyLight
    action:
      - choose:
          - conditions: >
              {{ trigger.event.data.Data.State | int in [0, 1, 2, 5, 6] }}
            sequence:
              - service: persistent_notification.create
                data:
                  title: "{{ 'Citofonata' if trigger.event.data.Data.State | int in [1, 2] else 'Doorbell No Ring' }}"
                  message: "{{ trigger.event.data }}"
          - conditions: >
              {{ trigger.event.data.Data.State | int == 8 }}
            sequence:
              - service: timer.start
                data:
                  entity_id: timer.Cancelletto_lock
                  duration: 00:00:02 # VTO Unlock Period
              - service: persistent_notification.create
                data:
                  title: Apertura
                  message: "{{ trigger.event.data }}"
          - conditions: >
              {{ trigger.event.data.Data.State | int == 9 }}
            sequence:
              - service: persistent_notification.create
                data:
                  title: Apertura Fallita
                  message: "{{ trigger.event.data }}"
          - conditions: >
              {{ trigger.event.data.Data.State | int == 11 }}
            sequence:
              - service: persistent_notification.create
                data:
                  title: Riavvio Citofono
                  message: "{{ trigger.event.data }}"
        default:
          - service: persistent_notification.create
            data:
              title: "Stato Ignoto {{ trigger.event.data.Data.State | int }}"
              message: "{{ trigger.event.data }}"
    