# 
#   ____                        _           
#  |  _ \ ___  ___ ___  _ __ __| | ___ _ __ 
#  | |_) / _ \/ __/ _ \| '__/ _` |/ _ \ '__|
#  |  _ <  __/ (_| (_) | | | (_| |  __/ |   
#  |_| \_\___|\___\___/|_|  \__,_|\___|_|   
#                                           
# 

##========================================================================================
##                                                                                      ##
##                                       Recorder                                       ##
##      The recorder integration is responsible for storing details in a database,      ##
##                  which then are handled by the history integration.                  ##
##                  https://www.home-assistant.io/integrations/recorder                 ##
##                                                                                      ##
##========================================================================================

# Recorder
recorder:
  # Generico
  auto_purge: true
  purge_keep_days: !secret recorder_purge_keep_days
  commit_interval: 1
  # Esclusioni
  exclude:
    # Domini
    domains:
      # Inputs
      - input_boolean
      - input_datetime
      - input_number
      - input_select
      - input_text
      # Cameras
      - camera
      # Automations
      - automation
      # Scripts 
      - script
      # Scenes
      - scene
    # Entità
    entities:
      # Time & Astronomy
      - sensor.time
      - sensor.time_utc
      - sensor.time_date
      - sensor.date
      - sensor.date_time
      - sensor.date_time_utc
      - sensor.date_time_iso
      - sensor.internet_time
      # System
      - sensor.uptime
      - sensor.system_uptime_time
      - sensor.last_boot
      - sensor.system_last_boot_time
      # System Log
      - counter.system_log_warning
      - counter.system_log_error
      - counter.system_log_fatal
  # -------------------------------------------------------------------------------------------------------------------

# Sensors
sensor:
  # Database SQL
  # Dimensioni Database SQL [Rilevato]
  - platform: filesize
    file_paths:
      - /config/home-assistant_v2.db
  # Dimensioni Database SQL [Elaborato]
  - platform: template
    sensors:
      recorder_sql_database_size:
        friendly_name: "Dimensioni Database"
        value_template: >-
          {% if states.sensor.home_assistant_v2_db.state %}
            {% if states.sensor.home_assistant_v2_db.state | float >= 0 %}
              {{ ( states.sensor.home_assistant_v2_db.state | float / 1000 ) | round(2) }}
            {% else %}
              Errore
            {% endif %}
          {% else %}
            Errore
          {% endif %}
        unit_of_measurement: 'GB'
        icon_template: >-
          {% if states.sensor.home_assistant_v2_db.state %}
            {% if states.sensor.home_assistant_v2_db.state | float >= 0 %}
              mdi:database
            {% else %}
              mdi:database-remove
            {% endif %}
          {% else %}
            mdi:database-remove
          {% endif %}
  # -------------------------------------------------------------------------------------------------------------------

# Automations
automation:
  # Database SQL
  - alias: 'Recorder - Aggiornamento Stato Database SQL Automatico'
    initial_state: true
    mode: single
    max_exceeded: silent
    trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      seconds: '/15'
    action:
    - service: script.turn_on
      entity_id: script.recorder_status_refresh
  # -------------------------------------------------------------------------------------------------------------------

# Scripts
script:
  # Database SQL
  recorder_status_refresh:
    alias: 'Aggiornamento Stato Database'
    icon: mdi:database-sync
    sequence:
    - service: homeassistant.update_entity
      entity_id:
        - sensor.home_assistant_v2_db
        - sensor.recorder_sql_database_size
  recorder_purge_clean:
    alias: 'Pulizia Database'
    icon: mdi:database-check
    sequence:
    - service: recorder.purge
      data:
        keep_days: !secret recorder_purge_keep_days
        repack: true
  recorder_purge_empty:
    alias: 'Svuotamento Database'
    icon: mdi:database-remove
    sequence:
    - service: recorder.purge
      data:
        keep_days: !secret recorder_purge_empty_days
        repack: true
  # -------------------------------------------------------------------------------------------------------------------
